server:
  error:
    whitelabel:
      enabled: false
    path: /error
spring:
  config:
    import: classpath:config/database.yml
  profiles:
    group:
      development: db-development
      production: db-production, application-production
      test: db-test
